Convert the recipe to rattler-build
conda-forge/onednn-feedstock pull request #78
Opened 2024-12-18 18:36 UTC by mgorny

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Involves the generic mapping of keys, renaming the Windows build script to `build-onednn.bat` (as rattler-build expects names to match), and replacing `track_features` with `down_prioritize_variant`. For the dynamic part of `description`, I've declared Jinja variables for the respective versions and put the new-style condition in `description` itself (thanks to @jaimergp for the suggestion!)

2024-12-18 18:38 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/recipe.yaml```) and found it was in an excellent condition.

2024-12-18 19:32 UTC, xhochy requested changes
As long as we don't have autotick bot updates, I don't want to maintain rattler-build recipes.

2024-12-18 20:23 UTC, mgorny commented
> As long as we don't have autotick bot updates, I don't want to maintain rattler-build recipes.

No problem, it was primarily a learning/testing experience for me.

2024-12-18 20:34 UTC, xhochy commented
> No problem, it was primarily a learning/testing experience for me.

👍 Then keep this PR and rebase it when the bot support has landed, then I'm extremely eager to merge.

2025-05-12 11:52 UTC, xhochy commented
If you rebase this, I'm now happy to merge it. All constraints are now fulfilled.

2025-05-12 12:59 UTC, mgorny commented
Sure, will do that in a minute.

2025-05-12 13:31 UTC, mgorny commented
Rebased and confirmed locally to work (for the openmp linux build, at least). FWICS the only changes on `main` were version number and checksum.

2025-05-13 09:52 UTC, xhochy approved these changes

2025-05-13 09:52 UTC, merged

2025-05-13 12:43 UTC, mgorny commented
Thank you!